import Head from 'next/head'
import { Advent_Pro, Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import DevJoke from './api/devjoke'

const inter = Inter({ subsets: ['latin'] })
const advpro = Advent_Pro({
    weight: '500',
    subsets: ['latin']
})


export default function Home() {

    function getDevJoke() {
        console.log("Tried to retrieve a Joke")
    }

    return (
        <>
            <Head>
                <title>Oddball io</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.description}>
                    <span className={advpro.className}>Oddboard</span>
                </div>
                <button onClick={getDevJoke}>Joke of the Day</button>
                <h2 id="joke"></h2>
            </main>
        </>
    )
}

Home.addJoke = function addJoke(home: Function) {
    return (
        //<DevJoke >{home}</DevJoke>
        ''
    )
}
