import Head from 'next/head'
import Image from 'next/image'
import { Advent_Pro, Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
const advpro = Advent_Pro({
    weight: '500',
    subsets: ['latin']
})



export default function Home() {

    function getQotd() {
        console.log("Retrieved Quote of the Day")
    }

    return (
        <>
            <Head>
                <title>Oddball io</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.description}>
                    <span className={advpro.className}>Oddboard</span>
                </div>
                <button onClick={getQotd}>Quote of the Day</button>
            </main>
        </>
    )
}
